# Generated by Django 5.1.7 on 2025-05-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('sports', 'Sports Car'), ('luxury', 'Luxury Car'), ('passenger', 'Passenger Vehicle'), ('goods', 'Goods Vehicle')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
    ]
