# Generated by Django 5.1.7 on 2025-05-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_alter_car_car_type_alter_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='pickup_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
